import { NextRequest, NextResponse } from 'next/server';
import { MedicationRequest, ServiceRequest, Appointment, Resource } from '@medplum/fhirtypes';
import { getMedplumClient } from '@/lib/medplum-client';
import sgMail from '@sendgrid/mail';

/**
 * Request body structure for execute endpoint
 */
interface ExecuteRequest {
  action: {
    type: 'medication' | 'lab' | 'imaging' | 'referral' | 'followup' | 'scheduling';
    description: string;
    resource: MedicationRequest | ServiceRequest | Appointment;
    email?: string; // For scheduling
    subject?: string; // For scheduling
    body?: string; // For scheduling
  };
  patientId: string; // Medplum Patient resource ID
}

// Hardcoded default email as requested
const TARGET_EMAIL = "adarsh.danda1@gmail.com";

/**
 * Response structure for successful execution
 */
interface ExecuteResponse {
  success: true;
  resourceId: string;
  resourceType: string;
  message: string;
}

/**
 * Execute endpoint - Creates FHIR resources in Medplum
 * 
 * This endpoint takes a draft clinical action (from /api/analyze) and:
 * 1. Attaches the patient reference
 * 2. Writes the FHIR resource to Medplum
 * 3. Returns the created resource ID
 * 
 * POST /api/execute
 * Body: { action: ClinicalAction, patientId: string }
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body: ExecuteRequest = await request.json();
    const { action, patientId } = body;

    // Validate required fields
    if (!action) {
      return NextResponse.json(
        { error: 'Missing required field: action' },
        { status: 400 }
      );
    }

    if (!patientId || typeof patientId !== 'string') {
      return NextResponse.json(
        { error: 'Missing or invalid required field: patientId' },
        { status: 400 }
      );
    }

    if (!action.resource) {
      return NextResponse.json(
        { error: 'Missing resource in action' },
        { status: 400 }
      );
    }

    // Validate resource type
    const resourceType = action.resource.resourceType;
    if (resourceType !== 'MedicationRequest' && resourceType !== 'ServiceRequest' && resourceType !== 'Appointment') {
      return NextResponse.json(
        { 
          error: `Invalid resource type: ${resourceType}. Expected MedicationRequest, ServiceRequest, or Appointment` 
        },
        { status: 400 }
      );
    }

    console.log(`[Execute] Processing ${resourceType} for patient ${patientId}`);
    console.log(`[Execute] Action type: ${action.type}, Description: ${action.description}`);

    // Handle Email Sending for Scheduling Actions
    if (action.type === 'scheduling') {
      console.log('📧 Processing scheduling action email...');
      
      if (process.env.SENDGRID_API_KEY) {
        try {
          sgMail.setApiKey(process.env.SENDGRID_API_KEY);
          
          const recipient = action.email || TARGET_EMAIL;

          const msg = {
            to: recipient,
            from: process.env.SENDGRID_FROM_EMAIL || 'adarsh.danda1@gmail.com', // Must be verified in SendGrid
            subject: action.subject || `New Meeting Request: ${action.description}`,
            text: action.body || `A new follow-up meeting has been suggested.\n\nDetails: ${action.description}\n\nPatient ID: ${patientId}`,
            html: `
              <h2>New Meeting Request</h2>
              <p><strong>Details:</strong> ${action.description}</p>
              <p><strong>Message:</strong> ${action.body || action.description}</p>
              <hr/>
              <p><em>Generated by Clinical Action Layer</em></p>
            `,
          };

          await sgMail.send(msg);
          console.log('✅ Email sent successfully to', recipient);
        } catch (emailError: any) {
          console.error('❌ Failed to send email:', emailError);
          if (emailError.response) {
            console.error(emailError.response.body);
          }
          // We continue to create the FHIR resource even if email fails
        }
      } else {
        console.warn('⚠️ SENDGRID_API_KEY not found. Email skipped.');
      }
    }

    // Get authenticated Medplum client
    let medplum;
    try {
      medplum = await getMedplumClient();
    } catch (authError) {
      console.error('[Execute] Medplum authentication failed:', authError);
      return NextResponse.json(
        { error: 'Failed to authenticate with Medplum' },
        { status: 503 }
      );
    }

    // Clone the resource to avoid mutating the original
    const resourceToCreate = { ...action.resource };

    // Attach patient reference to the resource
    if (resourceType === 'Appointment') {
        // For Appointment, the patient is a participant
        resourceToCreate.participant = [
            {
                actor: {
                    reference: `Patient/${patientId}`,
                    display: undefined
                },
                status: 'needs-action'
            },
            ...(resourceToCreate.participant || [])
        ];
    } else {
        // For MedicationRequest/ServiceRequest, patient is subject
        resourceToCreate.subject = {
            reference: `Patient/${patientId}`,
            display: undefined, 
        };
    }

    // Ensure status is "draft" or "proposed"
    if (resourceType === 'Appointment') {
        resourceToCreate.status = 'proposed';
    } else {
        resourceToCreate.status = 'draft';
        resourceToCreate.intent = 'order';
    }

    console.log('[Execute] Creating resource in Medplum:', {
      resourceType,
      patientId,
      status: resourceToCreate.status,
    });

    // Create resource in Medplum
    let createdResource: Resource;
    try {
      createdResource = await medplum.createResource(resourceToCreate as any);
      console.log(`[Execute] ✅ Successfully created ${resourceType} with ID: ${createdResource.id}`);
    } catch (createError: any) {
      console.error('[Execute] Medplum createResource failed:', createError);
      
      if (createError.message?.includes('Patient')) {
        return NextResponse.json(
          { 
            error: `Patient not found: ${patientId}`,
            details: 'The specified patient ID does not exist in Medplum' 
          },
          { status: 404 }
        );
      }

      return NextResponse.json(
        { 
          error: 'Failed to create resource in Medplum',
          details: createError.message || 'Unknown error'
        },
        { status: 500 }
      );
    }

    // Return success response
    const response: ExecuteResponse = {
      success: true,
      resourceId: createdResource.id!,
      resourceType: createdResource.resourceType!,
      message: `Successfully created ${createdResource.resourceType} for patient ${patientId}`,
    };

    return NextResponse.json(response, { status: 201 });

  } catch (error) {
    console.error('[Execute] Unexpected error:', error);
    
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Internal server error',
        details: error instanceof Error ? error.stack : undefined
      },
      { status: 500 }
    );
  }
}
