import { NextRequest, NextResponse } from "next/server";
import sgMail from '@sendgrid/mail';

// Hardcoded email as requested
const TARGET_EMAIL = "adarsh.danda1@gmail.com"; // TODO: Update this to your verified sender/recipient

export async function POST(request: NextRequest) {
  try {
    const { sessionId, actions } = await request.json();

    // Simulate EMR write delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Process actions (including Email sending)
    for (const action of actions) {
      if (action.type === 'scheduling') {
        console.log('📧 Processing scheduling action...');
        
        if (process.env.SENDGRID_API_KEY) {
          try {
            sgMail.setApiKey(process.env.SENDGRID_API_KEY);
            
            const recipient = action.email || TARGET_EMAIL;

            const msg = {
              to: recipient,
              from: process.env.SENDGRID_FROM_EMAIL || 'test@example.com', // Must be verified in SendGrid
              subject: action.subject || `New Meeting Request: ${action.title}`,
              text: action.body || `A new follow-up meeting has been suggested.\n\nReason: ${action.reason}\nSuggested Time: ${action.when}\n\nTranscript ID: ${sessionId}`,
              html: action.bodyHtml || `
                <h2>New Meeting Request</h2>
                <p><strong>Reason:</strong> ${action.reason}</p>
                <p><strong>Suggested Time:</strong> ${action.when}</p>
                <hr/>
                <p><em>Generated by Clinical Action Layer</em></p>
              `,
            };

            await sgMail.send(msg);
            console.log('✅ Email sent successfully to', recipient);
          } catch (emailError: any) {
            console.error('❌ Failed to send email:', emailError);
            if (emailError.response) {
              console.error(emailError.response.body);
            }
          }
        } else {
          console.warn('⚠️ SENDGRID_API_KEY not found. Email skipped.');
        }
      }
    }

    // Mark all actions as successfully applied
    const appliedActions = actions.map((action: any) => ({
      ...action,
      status: "approved",
      appliedAt: new Date().toISOString(),
      appliedToEMR: true,
    }));

    return NextResponse.json({
      success: true,
      appliedActions,
      message: `Successfully applied ${appliedActions.length} action(s) to Medplum EMR`,
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to apply actions to EMR" },
      { status: 500 }
    );
  }
}
